export const navigationLinks = [
    { href: "/", label: "Home" },
    { href: "/about", label: "About" },
    { href: "/hotels", label: "Hotel" },
    { href: "/trips", label: "Trip" },
    { href: "/rent-a-cars", label: "Rent a car" },
    { href: "/contack", label: "Contack" },
  ]

  export const packages = [
    {
      image: "/instagram/1.jpg",
      title: "Romantic Sri Lanka Honeymoon Package",
      location: "England, Maldives, Srilanka",
      duration: "7 Days - 5 Nights",
      price: "$900",
      oldPrice: "$1000",
      discount: "10% Off",
    },
    {
      image: "/instagram/2.jpg",
      title: "7 Days tour to Explore the Beauty of Philippines",
      location: "England, Maldives, Philippines",
      duration: "6 Days - 5 Nights",
      price: "$300",
    },
    {
      image: "/instagram/3.jpg",
      title: "Everest Base Camp Trek: See the Majestic Mt. Everest",
      location: "Annapurna, France, India",
      duration: "4 Days - 2 Nights",
      price: "$250",
      oldPrice: "$1500",
      discount: "83% Off",
    },
    {
      image: "/instagram/4.jpg",
      title: "Discover the Beauty of the Swiss Alps",
      location: "Switzerland, Austria",
      duration: "5 Days - 4 Nights",
      price: "$1,200",
    },
    {
      image: "/instagram/5.jpg",
      title: "A Magical Tour of Paris and Beyond",
      location: "Paris, France",
      duration: "3 Days - 2 Nights",
      price: "$750",
      oldPrice: "$900",
      discount: "15% Off",
    },
    {
      image: "/instagram/6.jpg",
      title: "African Safari Adventure",
      location: "Kenya, South Africa",
      duration: "8 Days - 7 Nights",
      price: "$2,100",
    },
    {
      image: "/instagram/7.jpg",
      title: "Explore the Wonders of Egypt",
      location: "Cairo, Egypt",
      duration: "6 Days - 5 Nights",
      price: "$1,000",
      oldPrice: "$1,200",
      discount: "20% Off",
    },
    {
      image: "/instagram/8.jpg",
      title: "An Exotic Getaway in Bali",
      location: "Bali, Indonesia",
      duration: "5 Days - 4 Nights",
      price: "$600",
    },
    {
      image: "/instagram/9.jpg",
      title: "Experience the Northern Lights in Iceland",
      location: "Reykjavik, Iceland",
      duration: "4 Days - 3 Nights",
      price: "$1,500",
      oldPrice: "$1,800",
      discount: "17% Off",
    },
    {
      image: "/instagram/10.jpg",
      title: "Explore the Ancient Temples of Cambodia",
      location: "Siem Reap, Cambodia",
      duration: "7 Days - 6 Nights",
      price: "$800",
    },
    {
      image: "/instagram/11.jpg",
      title: "A Luxurious Cruise to the Caribbean",
      location: "Caribbean Islands",
      duration: "10 Days - 9 Nights",
      price: "$3,000",
      oldPrice: "$3,500",
      discount: "14% Off",
    },
  ];

